name: rag-chatbot
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - langchain==1.0.8
      - pypdf==6.3.0
      - langchain-openai==1.0.3
      - langchain-community==0.4.1
      - langchain-text-splitters==1.0.0
      - langchain-ollama==1.0.0
      - sentence-transformers==5.1.2
      - streamlit==1.51.0
      - openai==2.8.1
      - faiss-cpu==1.13.0
      - unstructured==0.18.20